name: 🚀 Deploy

on:
  push:
    branches:
      - main
      - dev
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: write
  contents: read

jobs:
  lint:
    name: ⬣ Biome
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4

      - name: ⎔ Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - name: 🔍 Verify pnpm installation
        run: pnpm --version

      - name: ⎔ Setup node
        uses: actions/setup-node@v4
        with:
          cache: pnpm
          cache-dependency-path: ./package.json
          node-version: 20

      - name: 📥 Install deps
        run: pnpm install

      - name: 🔬 Lint
        run: pnpm run lint

  typecheck:
    name: ʦ TypeScript
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4

      - name: ⎔ Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - name: 🔍 Verify pnpm installation
        run: pnpm --version

      - name: ⎔ Setup node
        uses: actions/setup-node@v4
        with:
          cache: pnpm
          cache-dependency-path: ./package.json
          node-version: 20

      - name: 📥 Install deps
        run: pnpm install

      - name: 🛠 Generate Prisma client
        run: pnpm dlx prisma generate

      - name: 🔎 Type check
        run: pnpm run typecheck

  vitest:
    name: ⚡ Vitest
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4

      - name: ⎔ Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - name: 🔍 Verify pnpm installation
        run: pnpm --version

      - name: ⎔ Setup node
        uses: actions/setup-node@v4
        with:
          cache: pnpm
          cache-dependency-path: ./package.json
          node-version: 20

      - name: 📥 Install deps
        run: pnpm install

      - name: ⚡ Run vitest
        run: pnpm run test -- --coverage

  cypress:
    name: ⚫️ Cypress
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4

      - name: 🏄 Copy test env vars
        run: cp .env.example .env

      - name: ⎔ Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - name: 🔍 Verify pnpm installation
        run: pnpm --version

      - name: ⎔ Setup node
        uses: actions/setup-node@v4
        with:
          cache: pnpm
          cache-dependency-path: ./package.json
          node-version: 20

      - name: 📥 Install deps
        run: pnpm install

      - name: 🛠 Setup Database
        run: pnpm dlx prisma migrate reset --force

      - name: ⚙️ Build
        run: pnpm run build

      - name: 🌳 Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: pnpm run start:mocks
          wait-on: http://localhost:8811
        env:
          PORT: 8811

  deploy:
    name: 🚀 Deploy
    runs-on: ubuntu-latest
    needs: [lint, typecheck, vitest, cypress]
    # only deploy main/dev branch on pushes
    if: ${{ (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev') && github.event_name == 'push' }}

    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4

      - name: 👀 Read app name
        uses: SebRollen/toml-action@v1.2.0
        id: app_name
        with:
          file: fly.toml
          field: app

      - name: 🎈 Setup Fly
        uses: superfly/flyctl-actions/setup-flyctl@v1

      - name: 🚀 Deploy Staging
        if: ${{ github.ref == 'refs/heads/dev' }}
        run: flyctl deploy --remote-only --build-arg COMMIT_SHA=${{ github.sha }} --app ${{ steps.app_name.outputs.value }}-staging
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: 🚀 Deploy Production
        if: ${{ github.ref == 'refs/heads/main' }}
        run: flyctl deploy --remote-only --build-arg COMMIT_SHA=${{ github.sha }} --app ${{ steps.app_name.outputs.value }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}